export const newReleasesMock = {
  albums: {
    href: "https://api.spotify.com/v1/browse/new-releases?offset=0&limit=20",
    items: [
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/06HL4z0CvFAxyc27GXpf02"
            },
            href: "https://api.spotify.com/v1/artists/06HL4z0CvFAxyc27GXpf02",
            id: "06HL4z0CvFAxyc27GXpf02",
            name: "Taylor Swift",
            type: "artist",
            uri: "spotify:artist:06HL4z0CvFAxyc27GXpf02"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/21dd5QyItuoqvPkViQXlKf"
        },
        href: "https://api.spotify.com/v1/albums/21dd5QyItuoqvPkViQXlKf",
        id: "21dd5QyItuoqvPkViQXlKf",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/6441b3a54e720b0fab3646c89ef35869d559414d",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/eb084f648534258fe5f7cc2994ae01bf98f8318d",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/964f2be6463cabde9f14cf2ec3b49cc822e90c3d",
            width: 64
          }
        ],
        name: "You Need To Calm Down",
        release_date: "2019-06-14",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:21dd5QyItuoqvPkViQXlKf"
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/1iNqsUDUraNWrj00bqssQG"
            },
            href: "https://api.spotify.com/v1/artists/1iNqsUDUraNWrj00bqssQG",
            id: "1iNqsUDUraNWrj00bqssQG",
            name: "Dreamville",
            type: "artist",
            uri: "spotify:artist:1iNqsUDUraNWrj00bqssQG"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/3VTNWsdPxKZjJvEY87GivP"
        },
        href: "https://api.spotify.com/v1/albums/3VTNWsdPxKZjJvEY87GivP",
        id: "3VTNWsdPxKZjJvEY87GivP",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/0093ae3842b329d82f9900516e3cfca6fbc6572e",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/5dcc4b0f0e5e80e2c1bfbb2cd79492b0daf1c942",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/6bfe93e9ebcf259bf456c1c6eb840ec17020c2b1",
            width: 64
          }
        ],
        name: "1-888-88-DREAM",
        release_date: "2019-06-12",
        release_date_precision: "day",
        total_tracks: 2,
        type: "album",
        uri: "spotify:album:3VTNWsdPxKZjJvEY87GivP"
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/540vIaP2JwjQb9dm3aArA4"
            },
            href: "https://api.spotify.com/v1/artists/540vIaP2JwjQb9dm3aArA4",
            id: "540vIaP2JwjQb9dm3aArA4",
            name: "DJ Snake",
            type: "artist",
            uri: "spotify:artist:540vIaP2JwjQb9dm3aArA4"
          },
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/1vyhD5VmyZ7KMfW5gqLgo5"
            },
            href: "https://api.spotify.com/v1/artists/1vyhD5VmyZ7KMfW5gqLgo5",
            id: "1vyhD5VmyZ7KMfW5gqLgo5",
            name: "J Balvin",
            type: "artist",
            uri: "spotify:artist:1vyhD5VmyZ7KMfW5gqLgo5"
          },
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/5LHRHt1k9lMyONurDHEdrp"
            },
            href: "https://api.spotify.com/v1/artists/5LHRHt1k9lMyONurDHEdrp",
            id: "5LHRHt1k9lMyONurDHEdrp",
            name: "Tyga",
            type: "artist",
            uri: "spotify:artist:5LHRHt1k9lMyONurDHEdrp"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/3HXHo0qkSUO4M9p6PEnA01"
        },
        href: "https://api.spotify.com/v1/albums/3HXHo0qkSUO4M9p6PEnA01",
        id: "3HXHo0qkSUO4M9p6PEnA01",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/0c8ceca9558adee17787f683ac27f05aeddd03a5",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/812fdf3b05e657cffacafa6d7669f03e0b05a676",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/3c3c59174f57dff95be07fc3496fe57097c65cfc",
            width: 64
          }
        ],
        name: "Loco Contigo (with J. Balvin & Tyga)",
        release_date: "2019-06-13",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:3HXHo0qkSUO4M9p6PEnA01"
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/4AVFqumd2ogHFlRbKIjp1t"
            },
            href: "https://api.spotify.com/v1/artists/4AVFqumd2ogHFlRbKIjp1t",
            id: "4AVFqumd2ogHFlRbKIjp1t",
            name: "Alesso",
            type: "artist",
            uri: "spotify:artist:4AVFqumd2ogHFlRbKIjp1t"
          },
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/7vXDAI8JwjW531ouMGbfcp"
            },
            href: "https://api.spotify.com/v1/artists/7vXDAI8JwjW531ouMGbfcp",
            id: "7vXDAI8JwjW531ouMGbfcp",
            name: "TINI",
            type: "artist",
            uri: "spotify:artist:7vXDAI8JwjW531ouMGbfcp"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/0D26ZmfHtg7309j2TEKxnR"
        },
        href: "https://api.spotify.com/v1/albums/0D26ZmfHtg7309j2TEKxnR",
        id: "0D26ZmfHtg7309j2TEKxnR",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/a7b321cb5ec3bc57312d59e67dc7c586392fae1e",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/e358317dc28c2564e71ec99d0e2ec0dab2d86b92",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/c602ac9b853ae1266550afe2c30d0fa7856db1de",
            width: 64
          }
        ],
        name: "Sad Song (feat. TINI)",
        release_date: "2019-06-14",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:0D26ZmfHtg7309j2TEKxnR"
      },
      {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/6tbjWDEIzxoDsBA1FuhfPW"
            },
            href: "https://api.spotify.com/v1/artists/6tbjWDEIzxoDsBA1FuhfPW",
            id: "6tbjWDEIzxoDsBA1FuhfPW",
            name: "Madonna",
            type: "artist",
            uri: "spotify:artist:6tbjWDEIzxoDsBA1FuhfPW"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/1G2YEQPXaOj1JZwa3ZiGe8"
        },
        href: "https://api.spotify.com/v1/albums/1G2YEQPXaOj1JZwa3ZiGe8",
        id: "1G2YEQPXaOj1JZwa3ZiGe8",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/27adcbd547d0d84166fb7f8059b9fffc582f4610",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/79e98e2ba0ef706432acea6024a6b48124c89909",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/2a3f4123e1dbb1c1bb849c64c38eb1f1e377b482",
            width: 64
          }
        ],
        name: "Madame X (Deluxe)",
        release_date: "2019-06-14",
        release_date_precision: "day",
        total_tracks: 15,
        type: "album",
        uri: "spotify:album:1G2YEQPXaOj1JZwa3ZiGe8"
      },
      {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/7EQ0qTo7fWT7DPxmxtSYEc"
            },
            href: "https://api.spotify.com/v1/artists/7EQ0qTo7fWT7DPxmxtSYEc",
            id: "7EQ0qTo7fWT7DPxmxtSYEc",
            name: "Bastille",
            type: "artist",
            uri: "spotify:artist:7EQ0qTo7fWT7DPxmxtSYEc"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/2QzbL1DICo4xZnWr8Sw4fF"
        },
        href: "https://api.spotify.com/v1/albums/2QzbL1DICo4xZnWr8Sw4fF",
        id: "2QzbL1DICo4xZnWr8Sw4fF",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/963c7eb0b167ffb71f6ea7c707b848ce41978360",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/65af86c9cad14e724ed577b7ca267b2e5f7511dc",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/53e233947ac6eaf79704f5202581a5401c532578",
            width: 64
          }
        ],
        name: "Doom Days",
        release_date: "2019-06-14",
        release_date_precision: "day",
        total_tracks: 11,
        type: "album",
        uri: "spotify:album:2QzbL1DICo4xZnWr8Sw4fF"
      },
      {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/5XenQ7XfcvQdfIbpLEFaKQ"
            },
            href: "https://api.spotify.com/v1/artists/5XenQ7XfcvQdfIbpLEFaKQ",
            id: "5XenQ7XfcvQdfIbpLEFaKQ",
            name: "GoldLink",
            type: "artist",
            uri: "spotify:artist:5XenQ7XfcvQdfIbpLEFaKQ"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/790qROmQ1y4aPEYLcSkScH"
        },
        href: "https://api.spotify.com/v1/albums/790qROmQ1y4aPEYLcSkScH",
        id: "790qROmQ1y4aPEYLcSkScH",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/4808661ee5409b0788267f3bef288ea398efd4e4",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/77f84bf48210d71f790254c9239f869c49eeb192",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/00c82530c882dcbf249003b7fccc3ff0225bde6a",
            width: 64
          }
        ],
        name: "Diaspora",
        release_date: "2019-06-12",
        release_date_precision: "day",
        total_tracks: 14,
        type: "album",
        uri: "spotify:album:790qROmQ1y4aPEYLcSkScH"
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/4GvEc3ANtPPjt1ZJllr5Zl"
            },
            href: "https://api.spotify.com/v1/artists/4GvEc3ANtPPjt1ZJllr5Zl",
            id: "4GvEc3ANtPPjt1ZJllr5Zl",
            name: "Bazzi",
            type: "artist",
            uri: "spotify:artist:4GvEc3ANtPPjt1ZJllr5Zl"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/7ytUi1ApfKHaD2iJrOzjvw"
        },
        href: "https://api.spotify.com/v1/albums/7ytUi1ApfKHaD2iJrOzjvw",
        id: "7ytUi1ApfKHaD2iJrOzjvw",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/a785c9c46bd1171e812f079e8e1419999cf88aed",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/e91339d7b8d3e49f6c45fc2d236b4b1a7751b27e",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/1f6b3865e8e91d3e8eebd96846671d63c1f691dc",
            width: 64
          }
        ],
        name: "Focus (feat. 21 Savage)",
        release_date: "2019-06-13",
        release_date_precision: "day",
        total_tracks: 2,
        type: "album",
        uri: "spotify:album:7ytUi1ApfKHaD2iJrOzjvw"
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/5IH6FPUwQTxPSXurCrcIov"
            },
            href: "https://api.spotify.com/v1/artists/5IH6FPUwQTxPSXurCrcIov",
            id: "5IH6FPUwQTxPSXurCrcIov",
            name: "Alec Benjamin",
            type: "artist",
            uri: "spotify:artist:5IH6FPUwQTxPSXurCrcIov"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/0A5GgdYeE7UJDnBeXuZWma"
        },
        href: "https://api.spotify.com/v1/albums/0A5GgdYeE7UJDnBeXuZWma",
        id: "0A5GgdYeE7UJDnBeXuZWma",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/e0a7bbf6120bfae3694b3fa80eebbb10c00d8a33",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/f85b68a291ad4c3fc81b935f7a4ac57a5072355b",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/7a7ee0d3977a824501fc8df0eff5ba32503992de",
            width: 64
          }
        ],
        name: "Must Have Been The Wind",
        release_date: "2019-06-13",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:0A5GgdYeE7UJDnBeXuZWma"
      },
      {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/3uJx5SnOM59Li7lCxA3b29"
            },
            href: "https://api.spotify.com/v1/artists/3uJx5SnOM59Li7lCxA3b29",
            id: "3uJx5SnOM59Li7lCxA3b29",
            name: "Lil Keed",
            type: "artist",
            uri: "spotify:artist:3uJx5SnOM59Li7lCxA3b29"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/3JDiBSlLalqzv0GTEDRi8i"
        },
        href: "https://api.spotify.com/v1/albums/3JDiBSlLalqzv0GTEDRi8i",
        id: "3JDiBSlLalqzv0GTEDRi8i",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/d860d28b7a2ec1d8afbc8cbb3dc5b870bb6f20bc",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/08bba5b5f12899d9e51482a913662363e3dc7263",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/5f689396d659ddcca1ccfecbbb10cce4d9571bcb",
            width: 64
          }
        ],
        name: "Long Live Mexico",
        release_date: "2019-06-14",
        release_date_precision: "day",
        total_tracks: 20,
        type: "album",
        uri: "spotify:album:3JDiBSlLalqzv0GTEDRi8i"
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/3Fl1V19tmjt57oBdxXKAjJ"
            },
            href: "https://api.spotify.com/v1/artists/3Fl1V19tmjt57oBdxXKAjJ",
            id: "3Fl1V19tmjt57oBdxXKAjJ",
            name: "Blueface",
            type: "artist",
            uri: "spotify:artist:3Fl1V19tmjt57oBdxXKAjJ"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/5Fw2YiYO8raRGUdtuLogfj"
        },
        href: "https://api.spotify.com/v1/albums/5Fw2YiYO8raRGUdtuLogfj",
        id: "5Fw2YiYO8raRGUdtuLogfj",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/a6ca678b4f6ccb8ec56c2888e0bc83371535bbb3",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/8013689f0e9e30fcb303279b905a126d2dcbf98a",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/1646a2ad166dac37462f92cda14d0fe86da67455",
            width: 64
          }
        ],
        name: "Daddy",
        release_date: "2019-06-14",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:5Fw2YiYO8raRGUdtuLogfj"
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/3b8QkneNDz4JHKKKlLgYZg"
            },
            href: "https://api.spotify.com/v1/artists/3b8QkneNDz4JHKKKlLgYZg",
            id: "3b8QkneNDz4JHKKKlLgYZg",
            name: "Florida Georgia Line",
            type: "artist",
            uri: "spotify:artist:3b8QkneNDz4JHKKKlLgYZg"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/2O09dg5SeNA5sRJn0rf4D3"
        },
        href: "https://api.spotify.com/v1/albums/2O09dg5SeNA5sRJn0rf4D3",
        id: "2O09dg5SeNA5sRJn0rf4D3",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/7fac22e6f133d9ea069da4dc207e73104f24f40f",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/483def1a3b5e520b02454b545b8dca45f8b93818",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/5f00afb40b6a507de31b033d34f23b7d3d0d3667",
            width: 64
          }
        ],
        name: "Talk You Out Of It / Cruise (Acoustic Remixes)",
        release_date: "2019-06-14",
        release_date_precision: "day",
        total_tracks: 2,
        type: "album",
        uri: "spotify:album:2O09dg5SeNA5sRJn0rf4D3"
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/6xvpfMjWTougrRRtK7iikz"
            },
            href: "https://api.spotify.com/v1/artists/6xvpfMjWTougrRRtK7iikz",
            id: "6xvpfMjWTougrRRtK7iikz",
            name: "Mason Ramsey",
            type: "artist",
            uri: "spotify:artist:6xvpfMjWTougrRRtK7iikz"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/1nFV1vnP2kj0sdWklj3oWv"
        },
        href: "https://api.spotify.com/v1/albums/1nFV1vnP2kj0sdWklj3oWv",
        id: "1nFV1vnP2kj0sdWklj3oWv",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/1ab37c8fa21f6d6711b5eec15d77bc46f7e8fc4c",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/68baec1f596dc18a3895f04daf3e77e0f4e647f1",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/a188b1742173dc3bb2e3ee093a99e98d1dde6794",
            width: 64
          }
        ],
        name: "Twang",
        release_date: "2019-06-14",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:1nFV1vnP2kj0sdWklj3oWv"
      },
      {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/3eqjTLE0HfPfh78zjh6TqT"
            },
            href: "https://api.spotify.com/v1/artists/3eqjTLE0HfPfh78zjh6TqT",
            id: "3eqjTLE0HfPfh78zjh6TqT",
            name: "Bruce Springsteen",
            type: "artist",
            uri: "spotify:artist:3eqjTLE0HfPfh78zjh6TqT"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/6BhqPpIgY83rqoZ2L78Lte"
        },
        href: "https://api.spotify.com/v1/albums/6BhqPpIgY83rqoZ2L78Lte",
        id: "6BhqPpIgY83rqoZ2L78Lte",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/1675891ff0fdcb0c793cca5456c37255a619a8cd",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/1fe857bd563bab340ad7c1ebf0e0fe6b87bd66cd",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/561334a917ccce657a8b952e385fc54e32be082f",
            width: 64
          }
        ],
        name: "Western Stars",
        release_date: "2019-06-14",
        release_date_precision: "day",
        total_tracks: 13,
        type: "album",
        uri: "spotify:album:6BhqPpIgY83rqoZ2L78Lte"
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/13y7CgLHjMVRMDqxdx0Xdo"
            },
            href: "https://api.spotify.com/v1/artists/13y7CgLHjMVRMDqxdx0Xdo",
            id: "13y7CgLHjMVRMDqxdx0Xdo",
            name: "Gucci Mane",
            type: "artist",
            uri: "spotify:artist:13y7CgLHjMVRMDqxdx0Xdo"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/5aVUVfCVcpAdSOXQ9VWA2a"
        },
        href: "https://api.spotify.com/v1/albums/5aVUVfCVcpAdSOXQ9VWA2a",
        id: "5aVUVfCVcpAdSOXQ9VWA2a",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/a58e4fc1839fb5e6a94387bad9c24b7d7f16c3cb",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/8011c7ae081fcc208c00b03f69ba5b0c516001d3",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/a1037f9580aa130a6cbaf20451da83ab4ae0d827",
            width: 64
          }
        ],
        name: "Backwards (feat. Meek Mill)",
        release_date: "2019-06-13",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:5aVUVfCVcpAdSOXQ9VWA2a"
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/3tQx1LPXbsYjE9VwN1Peaa"
            },
            href: "https://api.spotify.com/v1/artists/3tQx1LPXbsYjE9VwN1Peaa",
            id: "3tQx1LPXbsYjE9VwN1Peaa",
            name: "Marc E. Bassy",
            type: "artist",
            uri: "spotify:artist:3tQx1LPXbsYjE9VwN1Peaa"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/3ENZoeAW1jkUvb4lxpxJl4"
        },
        href: "https://api.spotify.com/v1/albums/3ENZoeAW1jkUvb4lxpxJl4",
        id: "3ENZoeAW1jkUvb4lxpxJl4",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/15d54c7c1ac67750a444b8b059bcd6d63d0bb754",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/634ba53ac4fe1f0484d31a69b14d26cf9bfb60ea",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/0b2d5f22cbf1ecd950adc7262ba1d2c50206972d",
            width: 64
          }
        ],
        name: "Save Me",
        release_date: "2019-06-11",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:3ENZoeAW1jkUvb4lxpxJl4"
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/7sjttK1WcZeyLPn3IsQ62L"
            },
            href: "https://api.spotify.com/v1/artists/7sjttK1WcZeyLPn3IsQ62L",
            id: "7sjttK1WcZeyLPn3IsQ62L",
            name: "Noel Gallagher's High Flying Birds",
            type: "artist",
            uri: "spotify:artist:7sjttK1WcZeyLPn3IsQ62L"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AU",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DO",
          "DZ",
          "EC",
          "EG",
          "FI",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IL",
          "IN",
          "JO",
          "KW",
          "LB",
          "LI",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/59KvTCbW9rHU0D8S7DOR10"
        },
        href: "https://api.spotify.com/v1/albums/59KvTCbW9rHU0D8S7DOR10",
        id: "59KvTCbW9rHU0D8S7DOR10",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/c86f1fef30501931dd4521fdbe0b8604c8a7b6a6",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/a56854cd7bae5d59af414de3a4de566da1c468d8",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/bfee70f358b3062a28f309c153f5786030969b88",
            width: 64
          }
        ],
        name: "Black Star Dancing",
        release_date: "2019-06-14",
        release_date_precision: "day",
        total_tracks: 5,
        type: "album",
        uri: "spotify:album:59KvTCbW9rHU0D8S7DOR10"
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/2GHclqNVjqGuiE5mA7BEoc"
            },
            href: "https://api.spotify.com/v1/artists/2GHclqNVjqGuiE5mA7BEoc",
            id: "2GHclqNVjqGuiE5mA7BEoc",
            name: "Common",
            type: "artist",
            uri: "spotify:artist:2GHclqNVjqGuiE5mA7BEoc"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/5ASnPqVkvU50cwNlC6OoX6"
        },
        href: "https://api.spotify.com/v1/albums/5ASnPqVkvU50cwNlC6OoX6",
        id: "5ASnPqVkvU50cwNlC6OoX6",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/aa7e4ef5ecb3c94ecbbc16ca75ffaf12cacccfa6",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/fb5f423f7cade4fa928bed44c863e862b88fe49a",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/805688f86752c0894c5e957f9462832fffaa6997",
            width: 64
          }
        ],
        name: "HER Love (Feat. Daniel Caesar)",
        release_date: "2019-06-14",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:5ASnPqVkvU50cwNlC6OoX6"
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/3MZsBdqDrRTJihTHQrO6Dq"
            },
            href: "https://api.spotify.com/v1/artists/3MZsBdqDrRTJihTHQrO6Dq",
            id: "3MZsBdqDrRTJihTHQrO6Dq",
            name: "Joji",
            type: "artist",
            uri: "spotify:artist:3MZsBdqDrRTJihTHQrO6Dq"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/1cjgTku8zcYVHRi8QQH1XI"
        },
        href: "https://api.spotify.com/v1/albums/1cjgTku8zcYVHRi8QQH1XI",
        id: "1cjgTku8zcYVHRi8QQH1XI",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/8faadbea1a7ac966d6dd6f5d6ece9ec57e20cc89",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/e7a1e8765ea6fc6b19e907180c52ff8bc3fa8585",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/2fb33e6cdb5fd405cafc04fbe9c77a3314d369ad",
            width: 64
          }
        ],
        name: "Sanctuary",
        release_date: "2019-06-14",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:1cjgTku8zcYVHRi8QQH1XI"
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/4BYxqVkZyFjtik7crYLg5Q"
            },
            href: "https://api.spotify.com/v1/artists/4BYxqVkZyFjtik7crYLg5Q",
            id: "4BYxqVkZyFjtik7crYLg5Q",
            name: "Chris Young",
            type: "artist",
            uri: "spotify:artist:4BYxqVkZyFjtik7crYLg5Q"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/2Wz8zcM6HnbJFhZfetld95"
        },
        href: "https://api.spotify.com/v1/albums/2Wz8zcM6HnbJFhZfetld95",
        id: "2Wz8zcM6HnbJFhZfetld95",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/b2f9b6b1c746e536a0d500935c0aba2270e50a35",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/417c014f589def87e244e98410cbd76c3addd93b",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/71eb932607e0cb1f85967a06a7e79722e2de4944",
            width: 64
          }
        ],
        name: "Drowning",
        release_date: "2019-06-14",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:2Wz8zcM6HnbJFhZfetld95"
      }
    ],
    limit: 20,
    next: "https://api.spotify.com/v1/browse/new-releases?offset=20&limit=20",
    offset: 0,
    previous: null,
    total: 100
  }
};
